In [1]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
np.arange(5, 12)

array([ 5,  6,  7,  8,  9, 10, 11])

In [3]:
np.arange(1, 5, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [4]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.ravel(A)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.ravel(A, order='C')

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.ravel(A, order='F')

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [8]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.where(a % 2 == 0, a * 10, a / 10)

array([ 0. ,  0.1, 20. ,  0.3, 40. ,  0.5, 60. ,  0.7, 80. ,  0.9])

In [9]:
a = np.random.rand(10)
a

array([0.55078842, 0.83322535, 0.50401979, 0.41202144, 0.53401922,
       0.81203636, 0.86304881, 0.75363088, 0.22908859, 0.04878729])

In [10]:
np.where(a > 0.5, True, False)

array([ True,  True,  True, False,  True,  True,  True,  True, False,
       False])

In [11]:
np.where(a > 0.5, 1, -1)

array([ 1,  1,  1, -1,  1,  1,  1,  1, -1, -1])