In [1]:
import numpy as np

In [2]:
np.random.permutation(7)

array([1, 2, 3, 5, 6, 4, 0])

In [3]:
a = ['a', 'b', 'c', 'd', 'e']
np.random.permutation(a)

array(['a', 'd', 'c', 'b', 'e'], dtype='<U1')

In [4]:
arr = np.linspace(0, 10, 5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [5]:
arr_mix = np.random.permutation(arr)
arr_mix

array([ 5. , 10. ,  2.5,  7.5,  0. ])

In [6]:
index_mix = np.random.permutation(len(arr_mix))
index_mix

array([3, 2, 0, 4, 1])

In [7]:
arr[index_mix]

array([ 7.5,  5. ,  0. , 10. ,  2.5])