In [1]:
import numpy as np
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [2]:
m[1, 0]

5

In [3]:
m[1, :]

matrix([[5, 6, 7, 8]])

In [4]:
m[:, 2]

matrix([[3],
        [7],
        [5]])

In [5]:
m[1, 2:]

matrix([[7, 8]])

In [6]:
m[0:2, 1]

matrix([[2],
        [6]])

In [7]:
m[0:2, 1:3]

matrix([[2, 3],
        [6, 7]])

In [8]:
cols = [0, 1, 3]

In [9]:
m[:, cols]

matrix([[1, 2, 4],
        [5, 6, 8],
        [9, 1, 7]])