# Индивидуальное задание1

## Характеристикой столбца целочисленной матрицы назовем сумму модулей его отрицательных нечетных элементов. Переставляя столбцы заданной матрицы, расположить их в соответствий с ростом характеристик. Найти сумму элементов в тех столбцах, которые содержат хотя бы один отрицательный элемент. 

In [1]:
import numpy as np

In [2]:
# Создаем матрицу размером 5x5 со случайными целыми числами от -9 до 9
matrix = np.random.randint(-9, 10, size=(5, 5))
print("Исходная матрица:\n", matrix)

Исходная матрица:
 [[-2  4  7 -6  2]
 [ 6  5  2  8 -9]
 [ 4 -9 -6  5  9]
 [-3 -8  6  1 -7]
 [-5 -7 -6  3  1]]


In [3]:
# Вычисляем характеристики для каждого столбца
characteristics = np.sum(np.abs(matrix[matrix < 0][::2]), axis=0)
print("Характеристики столбцов:\n", characteristics)

Характеристики столбцов:
 36


In [4]:
# Сортируем столбцы матрицы по возрастанию характеристик
sorted_matrix = matrix[:, np.argsort(characteristics)]
print("Отсортированная матрица:\n", sorted_matrix)

Отсортированная матрица:
 [[-2]
 [ 6]
 [ 4]
 [-3]
 [-5]]


In [5]:
# Находим сумму элементов в столбцах, содержащих хотя бы один отрицательный элемент
sum_negative_columns = np.sum(sorted_matrix[:, np.any(sorted_matrix < 0, axis=0)], axis=0)
print("Сумма элементов в столбцах с отрицательными элементами:", sum_negative_columns.sum())

Сумма элементов в столбцах с отрицательными элементами: 0
